:toc:

== cmh-kicad-library

image:https://www.repostatus.org/badges/latest/active.svg[Project Status: Active – The project has reached a stable, usable state and is being actively developed, link=https://www.repostatus.org/#active] image:https://img.shields.io/badge/kicad-%3E%3D8.0-critical[Required KiCad Version] image:https://img.shields.io/github/license/cmhettinger/cmh-kicad-library[License] image:https://img.shields.io/github/v/release/cmhettinger/cmh-kicad-library[GitHub release (latest SemVer)] image:https://img.shields.io/badge/symbols-1-informational[Symbols] image:https://img.shields.io/badge/footprints-1-informational[Footprints] image:https://img.shields.io/github/downloads/cmhettinger/cmh-kicad-library/total[Downloads]

This is a library of various KiCad schematic symbols and footprints.

=== KiCad Version Compatibility
This library has only been tested with KiCad 8.

=== Library Installation
To install this library in KiCad 8, follow the steps below to use KiCad's Package and Content Manager (PCM):

* Download the `cmh-kicad-library-x.x.x-addon.zip` library file from https://github.com/cmhettinger/cmh-kicad-library/releases[Releases]
* Open KiCad
* Click "Plugin and Content Manager"
* Click "Install from File..."
* Select the library file you downloaded in step 1
* The library should now be listed in the "Installed" tab.
* Close the Plugin and Content Manager

=== License

cmh-kicad-library © 2024 by cmhetttinger is licensed under link:http://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1[CC BY-SA 4.0]
image:https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1[CC, width=20, height=20]
image:https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1[BY, width=20, height=20]
image:https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1[SA, width=20, height=20]

Except as otherwise noted, all content of this library is licensed under the 
link:https://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution-ShareAlike 4.0 International License], with the following additional exception:

[quote]
To the extent that the creation of electronic designs that use the Licensed Material can be considered to be Adapted Material, the Licensor waives Section 3 of the Public License with respect to these electronic designs and any generated files which incorporate data provided as part of the Licensed Material.
[end]

=== What does the license mean?

cmh-kicad-library is licensed in such a way to ensure free use of library data for commercial, closed, and non-commercial projects without restriction. cmhettinger does not wish to exert any control over designs produced using the library data, or force users to reveal proprietary information contained in their designs. Neither do I wish to force users to attribute the cmh-kicad-library _within their design_.

Use of the library data in a project does not (by itself) require that the design or any files generated from the design are licensed under the CC-BY-SA 4.0 License. You are free to use the library data in your own projects without the obligation to share your project files under this or any other license agreement.

However, if you wish to redistribute the cmh-kicad-library, or parts thereof (including in modified form) as a collection then the exception above does not apply. Redistributed library collections must be shared under the same license agreement. Under these circumstances, the libraries must also retain attribution information, including the license documents which are distributed with the library files.

**Disclaimer of Warranties and Limitation of Liability**

* Unless otherwise separately undertaken by the Licensor, to the extent possible, the Licensor offers the Licensed Material as-is and as-available, and makes no representations or warranties of any kind concerning the Licensed Material, whether express, implied, statutory, or other. This includes, without limitation, warranties of title, merchantability, fitness for a particular purpose, non-infringement, absence of latent or other defects, accuracy, or the presence or absence of errors, whether or not known or discoverable. Where disclaimers of warranties are not allowed in full or in part, this disclaimer may not apply to You.
* To the extent possible, in no event will the Licensor be liable to You on any legal theory (including, without limitation, negligence) or otherwise for any direct, special, indirect, incidental, consequential, punitive, exemplary, or other losses, costs, expenses, or damages arising out of this Public License or use of the Licensed Material, even if the Licensor has been advised of the possibility of such losses, costs, expenses, or damages. Where a limitation of liability is not allowed in full or in part, this limitation may not apply to You.
* The disclaimer of warranties and limitation of liability provided above shall be interpreted in a manner that, to the extent possible, most closely approximates an absolute disclaimer and waiver of all liability.

== Library Symbols

* ESP32-C3-DevKitC-02

== Library Footprints

* ESP32-C3-DevKitC-02

== KiCad Official Links

* https://www.kicad.org[KiCad]
* https://klc.kicad.org[KiCad Library Conventions]
* https://kicad.github.io[KiCad Official Libraries]
* https://gitlab.com/kicad/libraries[KiCad Official Libraries (gitlab)]
* https://dev-docs.kicad.org/en/addons[KiCad Addon Documentation]
* https://dev-docs.kicad.org/en/file-formats/sexpr-intro/index.html[KiCad S-Expression Format]