:toc:

== cmh-kicad-library

image:https://www.repostatus.org/badges/latest/active.svg[Project Status: Active – The project has reached a stable, usable state and is being actively developed, link=https://www.repostatus.org/#active] image:https://img.shields.io/badge/kicad-%3E%3D8.0-critical[Required KiCad Version] image:https://img.shields.io/github/license/cmhettinger/cmh-kicad-library[License] image:https://img.shields.io/github/v/release/cmhettinger/cmh-kicad-library[GitHub release (latest SemVer)] image:https://img.shields.io/badge/symbols-1-informational[Symbols] image:https://img.shields.io/github/downloads/cmhettinger/cmh-kicad-library/total[Downloads]


  _    _               _   _ _ _                          
 | |  (_)             | | | (_) |                         
 | | ___  ___ __ _  __| | | |_| |__  _ __ __ _ _ __ _   _ 
 | |/ / |/ __/ _` |/ _` | | | | '_ \| '__/ _` | '__| | | |
 |   <| | (_| (_| | (_| | | | | |_) | | | (_| | |  | |_| |
 |_|\_\_|\___\__,_|\__,_| |_|_|_.__/|_|  \__,_|_|   \__, |
                                                     __/ |
                                                    |___/ 

This is a library of KiCad schematic symbols for a variety of microchips and components.

=== KiCad Version Compatibility
This library has only been tested with KiCad 8.

=== Library Installation
To install this library in KiCad 8, follow the steps below to use KiCad's Package and Content Manager (PCM):

* Download the `cmh-kicad-library-x.x.x-addon.zip` library file from the https://github.com/cmhettinger/cmh-kicad-library/releases[Releases page]
* Open KiCad
* Click "Plugin and Content Manager"
* Click "Install from File..."
* Select the library file you downloaded in step 1
* The library should now be listed in the "Installed" tab.
* Close the Plugin and Content Manager

=== License

Copyright 2024, link:https://github.com/cmhettinger[cmhettinger]

Except as otherwise noted, all content of this library is licensed under the 
link:https://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution-ShareAlike 4.0 International License], with the following additional exception:

[quote]
To the extent that the creation of electronic designs that use the Licensed Material can be considered to be Adapted Material, the Licensor waives Section 3 of the Public License with respect to these electronic designs and any generated files which incorporate data provided as part of the Licensed Material.
[end]

link:https://github.com/cmhettinger/cmh-kicad-library[cmh-kicad-library] by link:https://github.com/cmhettinger[cmhetttinger] is licensed under link:http://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1[CC BY-SA 4.0]
image:https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1[CC]
image:https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1[BY]
image:https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1[SA]

== KiCad Official Links

* https://www.kicad.org/
* https://klc.kicad.org/
* https://kicad.github.io/
