:toc:

== cmh-kicad-library

image:https://www.repostatus.org/badges/latest/active.svg[Project Status: Active – The project has reached a stable, usable state and is being actively developed, link=https://www.repostatus.org/#active] image:https://img.shields.io/badge/kicad-%3E%3D8.0-critical[Required KiCad Version] image:https://img.shields.io/github/license/cmhettinger/cmh-kicad-library[License] image:https://img.shields.io/github/v/release/cmhettinger/cmh-kicad-library[GitHub release (latest SemVer)] image:https://img.shields.io/badge/symbols-1-informational[Symbols] image:https://img.shields.io/github/downloads/cmhettinger/cmh-kicad-library/total[Downloads]


  _    _               _   _ _ _                          
 | |  (_)             | | | (_) |                         
 | | ___  ___ __ _  __| | | |_| |__  _ __ __ _ _ __ _   _ 
 | |/ / |/ __/ _` |/ _` | | | | '_ \| '__/ _` | '__| | | |
 |   <| | (_| (_| | (_| | | | | |_) | | | (_| | |  | |_| |
 |_|\_\_|\___\__,_|\__,_| |_|_|_.__/|_|  \__,_|_|   \__, |
                                                     __/ |
                                                    |___/ 

This is a library of KiCad schematic symbols for a variety of microchips and components.

=== KiCad Version Compatibility
This library has only been tested with KiCad 8.

=== Library Installation
To install this library in KiCad 8, follow the steps below to use KiCad's Package and Content Manager (PCM):

* Download the `cmh-kicad-library-x.x.x-addon.zip` library file from the https://github.com/cmhettinger/cmh-kicad-library/releases[Releases page]
* Open KiCad
* Click "Plugin and Content Manager"
* Click "Install from File..."
* Select the library file you downloaded in step 1
* The library should now be listed in the "Installed" tab.
* Close the Plugin and Content Manager

== KiCad Official Links

* https://www.kicad.org/
* https://klc.kicad.org/
* https://kicad.github.io/
